Fix build with GCC 11 and std=gnu++14
Build fails with GCC 11 and std=gnu++14 because it cannot find NULL.
Noticed this while building latest Amiberry master for Batocera.

Fixed by including <cstddef> in floppybridge_abstract.h. Below is the
error output for reference:

g++-11 -std=gnu++14 -shared -fPIC -ldl -Ifloppybridge -Iwindows -o FloppyBridge.so floppybridge/ArduinoFloppyBridge.cpp floppybridge/ArduinoInterface.cpp floppybridge/CommonBridgeTemplate.cpp floppybridge/ftdi.cpp floppybridge/GreaseWeazleBridge.cpp floppybridge/GreaseWeazleInterface.cpp floppybridge/RotationExtractor.cpp floppybridge/SerialIO.cpp floppybridge/SuperCardProBridge.cpp floppybridge/SuperCardProInterface.cpp windows/FloppyBridge.cpp
In file included from floppybridge/ArduinoFloppyBridge.h:37,
                 from floppybridge/floppybridge_config.h:41,
                 from floppybridge/ArduinoFloppyBridge.cpp:32:
floppybridge/floppybridge_abstract.h: In member function 'virtual const char* FloppyDiskBridge::getLastErrorMessage()':
floppybridge/floppybridge_abstract.h:80:60: error: 'NULL' was not declared in this scope
   80 |         virtual const char* getLastErrorMessage() { return NULL; }
      |                                                            ^~~~
In file included from floppybridge/ArduinoFloppyBridge.h:37,
                 from floppybridge/floppybridge_config.h:41,
                 from floppybridge/ArduinoFloppyBridge.cpp:32:
floppybridge/floppybridge_abstract.h:25:1: note: 'NULL' is defined in header '<cstddef>'; did you forget to '#include <cstddef>'?
   24 | #include <functional>
  +++ |+#include <cstddef>
   25 |